{
 "title": "HookTrace Dashboard",
 "description": "Hooktrace dashboard ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Delivery Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(hooktrace_delivery_latency_seconds_bucket[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(hooktrace_delivery_latency_seconds_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(hooktrace_delivery_latency_seconds_bucket[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Rejected Webhooks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hooktrace_webhooks_invalid_signature_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "retries/sec" } },
   "targets": [
    { "expr": "hooktrace_events_retried_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Delivery Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "hooktrace_events_delivered_total",
     "legendFormat": "Delivered"
    },
    { "expr": "hooktrace_events_failed_total", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Incoming Webhooks / sec",
   "type": "timeseries",
   "description": "Incoming Webhooks per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hooktrace_webhooks_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}