"""initial schema

Revision ID: 86b50cf9cb23
Revises: 
Create Date: 2026-03-04 00:16:18.456680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86b50cf9cb23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('provider_id', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email')
    )
    op.add_column('webhook_events', sa.Column('route_id', sa.Integer(), nullable=True))
    op.alter_column('webhook_events', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=True)
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_idempotency_key'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_route'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_token'), table_name='webhook_events')
    op.create_foreign_key(None, 'webhook_events', 'webhook_routes', ['route_id'], ['id'])
    op.drop_column('webhook_events', 'attempt_count')
    op.drop_column('webhook_events', 'next_retry_at')
    op.drop_column('webhook_events', 'last_error')
    op.drop_column('webhook_events', 'route')
    op.drop_column('webhook_events', 'token')
    op.drop_column('webhook_events', 'provider')
    op.drop_column('webhook_events', 'delivery_target')
    op.drop_column('webhook_events', 'idempotency_key')
    op.drop_column('webhook_events', 'headers')
    op.add_column('webhook_routes', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_webhook_routes_id'), 'webhook_routes', ['id'], unique=False)
    op.create_foreign_key(None, 'webhook_routes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_routes', type_='foreignkey')
    op.drop_index(op.f('ix_webhook_routes_id'), table_name='webhook_routes')
    op.drop_column('webhook_routes', 'user_id')
    op.add_column('webhook_events', sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('webhook_events', sa.Column('idempotency_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('webhook_events', sa.Column('delivery_target', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('webhook_events', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('webhook_events', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('webhook_events', sa.Column('route', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('webhook_events', sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('webhook_events', sa.Column('next_retry_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('webhook_events', sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'webhook_events', type_='foreignkey')
    op.create_index(op.f('ix_webhook_events_token'), 'webhook_events', ['token'], unique=False)
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_events_route'), 'webhook_events', ['route'], unique=False)
    op.create_index(op.f('ix_webhook_events_idempotency_key'), 'webhook_events', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.alter_column('webhook_events', 'payload',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('webhook_events', 'route_id')
    op.drop_table('users')
    # ### end Alembic commands ###
